# ============================================
# Docker Compose - Development Override
# ============================================
# Uso: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    environment:
      POSTGRES_DB: nest_monorepo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  api:
    build:
      target: builder
    volumes:
      - ./src/apps/api:/app/src/apps/api:delegated
      - ./src/libs:/app/src/libs:delegated
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=nest_monorepo
      - NOTIFICATION_QUEUE_DRIVER=pgboss
      - NOTIFICATION_CRON_ENABLED=true
      - NOTIFICATION_CRON_EXPRESSION=*/5 * * * *
      - NOTIFICATION_WORKER_ENABLED=true
      - NOTIFICATION_MAX_ATTEMPTS=5
      - NOTIFICATION_RETRY_BACKOFF=true
      - NOTIFICATION_DLQ_NAME=notifications.dead-letter
      - NOTIFICATION_ACTIVE_CHANNELS=IN_APP
      - APP_TIMEZONE=UTC
    depends_on:
      postgres:
        condition: service_healthy
    command: npx nx serve api --host=0.0.0.0

  web:
    build:
      context: .
      dockerfile: src/apps/web/Dockerfile.dev
    volumes:
      - ./src/apps/web:/app/src/apps/web:delegated
      - ./src/libs:/app/src/libs:delegated
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: npx nx serve web --host=0.0.0.0

